services:
  customer-db:
    image: postgres:15
    container_name: customer-db
    environment:
      POSTGRES_DB: ${DB_CUSTOMER_NAME}
      POSTGRES_USER: ${DB_CUSTOMER_USER}
      POSTGRES_PASSWORD: ${DB_CUSTOMER_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - customer-db-data:/var/lib/postgresql/data

  invoice-db:
    image: postgres:15
    container_name: invoice-db
    environment:
      POSTGRES_DB: ${DB_INVOICE_NAME}
      POSTGRES_USER: ${DB_INVOICE_USER}
      POSTGRES_PASSWORD: ${DB_INVOICE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - invoice-db-data:/var/lib/postgresql/data

  customer-service:
    build: ./customer-service
    container_name: customer-service
    depends_on:
      - customer-db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-db:5432/${DB_CUSTOMER_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_CUSTOMER_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_CUSTOMER_PASSWORD}

  invoice-service:
    build: ./invoice-service
    container_name: invoice-service
    depends_on:
      - invoice-db
      - customer-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://invoice-db:5432/${DB_INVOICE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_INVOICE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_INVOICE_PASSWORD}
      CUSTOMER_SERVICE_URL: http://customer-service:8080
      
volumes:
  customer-db-data:
  invoice-db-data: