spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_CUSTOMER_NAME}
    username: ${DB_CUSTOMER_USER}
    password: ${DB_CUSTOMER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update